import type { ContentDraft } from "@prisma/client";

/** Assemble a draft's full text for checks and exports. */
export function draftFullText(d: ContentDraft): string {
  return [
    d.hook ?? "",
    d.body ?? "",
    d.caption ?? "",
    d.cta ?? "",
    d.visualNotes ?? "",
  ]
    .filter(Boolean)
    .join("\n\n");
}

export type ExportFormat = "markdown" | "json" | "text";

/** Build a downloadable/copyable document from a draft. */
export function draftToExport(
  d: ContentDraft,
  format: ExportFormat,
  profileName?: string | null
): string {
  const hashtags = (d.hashtags ?? "").split(",").map((h) => h.trim()).filter(Boolean);
  const storyboard = parseJson<Array<Record<string, string>>>(d.storyboard, []);
  const artboard = parseJson<Record<string, unknown> | null>(d.imagePrompt, null);
  const design = parseJson<Record<string, unknown> | null>(d.designSpec, null);

  const meta = {
    title: d.title,
    platform: d.platform,
    format: d.format,
    goal: d.goal,
    audience: d.audience,
    profile: profileName ?? null,
    status: d.status,
    // Record how it was made — never claim AI for generator output.
    generatedBy: d.generationMode === "llm" ? `ai:${d.model ?? "unknown-model"}` : "built-in generator",
    exportedAt: new Date().toISOString(),
  };

  if (format === "json") {
    return JSON.stringify(
      {
        ...meta,
        hook: d.hook,
        body: d.body,
        caption: d.caption,
        hashtags,
        cta: d.cta,
        visualDirection: d.visualNotes,
        storyboard,
        artboard,
        design,
      },
      null,
      2
    );
  }

  const shotList = storyboard.length
    ? [
        `## Shot list`,
        storyboard
          .map((s) =>
            [
              `### Shot ${s.index}${s.timecode && s.timecode !== "—" ? ` · ${s.timecode}` : ""}`,
              s.shot ? `- **Shot:** ${s.shot}` : "",
              s.onScreen ? `- **On screen:** ${s.onScreen}` : "",
              s.voiceover && s.voiceover !== "—" ? `- **Voiceover:** ${s.voiceover}` : "",
              s.transition ? `- **Transition:** ${s.transition}` : "",
            ]
              .filter(Boolean)
              .join("\n")
          )
          .join("\n\n"),
      ].join("\n")
    : [];

  const designBlock = design
    ? [
        `## Design spec`,
        design.typography ? `- **Typography:** ${design.typography}` : "",
        design.layout ? `- **Layout:** ${design.layout}` : "",
        design.motion ? `- **Motion:** ${design.motion}` : "",
      ]
        .filter(Boolean)
        .join("\n")
    : [];

  if (format === "markdown") {
    return [
      `# ${d.title}`,
      ``,
      `> ${meta.platform} · ${meta.format ?? "post"} · ${meta.goal ?? "no goal"}`,
      profileName ? `> Brand voice: ${profileName}` : `> Generic draft (no profile)`,
      `> Generated by: ${meta.generatedBy}`,
      ``,
      `## Hook`,
      d.hook ?? "",
      ``,
      `## Content`,
      d.body ?? "",
      ``,
      `## Caption`,
      d.caption ?? "",
      ``,
      `## Call to action`,
      d.cta ?? "",
      ``,
      `## Hashtags`,
      hashtags.join(" "),
      ``,
      `## Visual direction`,
      d.visualNotes ?? "",
      ...(shotList.length ? [``, ...shotList] : []),
      ...(designBlock.length ? [``, ...designBlock] : []),
    ].join("\n");
  }

  // plain text
  return [
    d.hook,
    "",
    d.body,
    "",
    d.caption,
    "",
    hashtags.join(" "),
    "",
    d.cta,
    ...(storyboard.length
      ? ["", ...storyboard.map((s) => `SHOT ${s.index} — ${s.shot}${s.onScreen ? ` | ${s.onScreen}` : ""}`)]
      : []),
  ]
    .filter((x) => x !== undefined && x !== "")
    .join("\n\n");
}

function parseJson<T>(raw: string | null | undefined, fallback: T): T {
  if (!raw) return fallback;
  try {
    return JSON.parse(raw) as T;
  } catch {
    return fallback;
  }
}
