"use server";

import { z } from "zod";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { getCurrentUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { transformDraft, type TransformKind } from "@/lib/transforms";
import type { GeneratedDraft } from "@/lib/generate";
import { generateContent } from "@/lib/ai";
import { translateDraft, LANGUAGES } from "@/lib/translate";

/** Every structured field a GeneratedDraft maps onto, for persistence. */
function draftFields(d: GeneratedDraft) {
  return {
    title: d.title,
    hook: d.hook,
    body: d.body,
    caption: d.caption,
    hashtags: d.hashtags.join(", "),
    cta: d.cta,
    visualNotes: d.visualDirection,
    storyboard: JSON.stringify(d.storyboard),
    imagePrompt: JSON.stringify(d.artboard),
    designSpec: JSON.stringify(d.design),
  };
}

/** Load a draft the signed-in user owns, with its versions. */
async function ownedDraft(id: string) {
  const user = await getCurrentUser();
  if (!user) redirect("/login");
  const draft = await prisma.contentDraft.findFirst({
    where: { id, userId: user.id },
    include: { profile: true },
  });
  if (!draft) redirect("/drafts");
  return draft;
}

function toGenerated(draft: {
  title: string;
  hook: string | null;
  body: string | null;
  caption: string | null;
  hashtags: string | null;
  cta: string | null;
  visualNotes: string | null;
  platform: string;
  goal: string | null;
  format: string | null;
  audience: string | null;
  storyboard?: string | null;
  imagePrompt?: string | null;
  designSpec?: string | null;
}): GeneratedDraft {
  // Structured extras are stored as JSON. A malformed blob must not break
  // editing, so each parse is guarded and falls back to an empty value.
  const parse = <T,>(raw: string | null | undefined, fallback: T): T => {
    if (!raw) return fallback;
    try {
      return JSON.parse(raw) as T;
    } catch {
      return fallback;
    }
  };

  return {
    title: draft.title,
    hook: draft.hook ?? "",
    body: draft.body ?? "",
    caption: draft.caption ?? "",
    hashtags: (draft.hashtags ?? "").split(",").map((h) => h.trim()).filter(Boolean),
    cta: draft.cta ?? "",
    visualDirection: draft.visualNotes ?? "",
    platform: draft.platform,
    goal: draft.goal ?? "",
    format: draft.format ?? "post",
    audience: draft.audience ?? null,
    storyboard: parse(draft.storyboard, []),
    artboard: parse(draft.imagePrompt, null as unknown as GeneratedDraft["artboard"]),
    design: parse(draft.designSpec, null as unknown as GeneratedDraft["design"]),
  };
}

async function snapshotVersion(draftId: string, label: string, d: GeneratedDraft) {
  await prisma.draftVersion.create({
    data: {
      draftId,
      label,
      content: JSON.stringify(d),
    },
  });
}

/* ---------- apply a transformation ---------- */

export async function applyTransform(formData: FormData) {
  const id = String(formData.get("id") ?? "");
  const kind = String(formData.get("kind") ?? "regenerate") as TransformKind;

  const draft = await ownedDraft(id);
  const result = transformDraft(kind, toGenerated(draft));

  const d = result.draft;
  await prisma.contentDraft.update({
    where: { id },
    data: {
      ...draftFields(d),
      // A transform edits the copy; the visual spec still matches the draft,
      // so "generated by" provenance is unchanged.
    },
  });

  await snapshotVersion(id, result.label, d);
  revalidatePath(`/drafts/${id}`);
  redirect(`/drafts/${id}?notice=${encodeURIComponent(`${result.label} — ${result.note}`)}`);
}

/* ---------- full regeneration (new angle, everything recomposed) ---------- */

export async function regenerateDraft(formData: FormData) {
  const id = String(formData.get("id") ?? "");
  const draft = await ownedDraft(id);

  const current = toGenerated(draft);
  const nextVariant = (draft.variant ?? 0) + 1;

  // Regenerate through the same pipeline as the original creation, so a
  // configured provider is used here too.
  const result = await generateContent({
    idea: draft.idea ?? "",
    profile: draft.profile
      ? {
          name: draft.profile.name,
          tone: draft.profile.tone,
          language: draft.profile.language,
          wordsToUse: draft.profile.wordsToUse,
          wordsToAvoid: draft.profile.wordsToAvoid,
          audience: draft.profile.audience,
          niche: draft.profile.niche,
          offerings: draft.profile.offerings,
          colors: draft.profile.colors,
          guidelines: draft.profile.guidelines,
          description: draft.profile.description,
          styleAnalysis: draft.profile.styleAnalysis,
        }
      : null,
    audience: draft.audience,
    platform: draft.platform,
    goal: draft.goal ?? "Awareness",
    format: draft.format ?? "post",
    variant: nextVariant,
  });

  // Keep the previous state, then write the new one.
  await snapshotVersion(id, `Before regeneration (angle ${nextVariant + 1})`, current);
  await prisma.contentDraft.update({
    where: { id },
    data: {
      ...draftFields(result.draft),
      variant: nextVariant,
      generationMode: result.mode,
      model: result.model,
    },
  });

  revalidatePath(`/drafts/${id}`);
  const notice =
    result.mode === "llm"
      ? `Regenerated with ${result.model} — angle ${nextVariant + 1}. Previous version kept in history.`
      : `Regenerated (built-in generator, angle ${nextVariant + 1}) — previous version kept in history.`;
  redirect(`/drafts/${id}?notice=${encodeURIComponent(notice)}`);
}

/* ---------- translate ---------- */

export async function translateDraftAction(formData: FormData) {
  const id = String(formData.get("id") ?? "");
  const language = String(formData.get("language") ?? "hi");
  const draft = await ownedDraft(id);

  const current = toGenerated(draft);
  const translated = await translateDraft(current, language);
  const label = LANGUAGES.find((l) => l.code === language)?.label ?? language;

  await snapshotVersion(id, `Before translation (${label})`, current);

  const updated: GeneratedDraft = {
    ...current,
    hook: translated.hook,
    caption: translated.caption,
    cta: translated.cta,
  };

  await prisma.contentDraft.update({
    where: { id },
    data: draftFields(updated),
  });

  revalidatePath(`/drafts/${id}`);
  const notice =
    translated.via === "llm"
      ? `Translated into ${label} by the configured AI provider. Original kept in history.`
      : `Marked for ${label} translation. No AI provider is configured, so Draftly could not translate it — add a key in Settings to enable real translation. Original kept in history.`;
  redirect(`/drafts/${id}?notice=${encodeURIComponent(notice)}`);
}

/* ---------- save user edits ---------- */

const editSchema = z.object({
  hook: z.string().max(2000),
  body: z.string().max(10000),
  cta: z.string().max(1000),
  hashtags: z.string().max(1000),
});

export async function saveEdits(formData: FormData) {
  const id = String(formData.get("id") ?? "");
  const draft = await ownedDraft(id);

  const parsed = editSchema.safeParse({
    hook: String(formData.get("hook") ?? ""),
    body: String(formData.get("body") ?? ""),
    cta: String(formData.get("cta") ?? ""),
    hashtags: String(formData.get("hashtags") ?? ""),
  });

  if (!parsed.success) {
    redirect(`/drafts/${id}?notice=${encodeURIComponent("Could not save — check field lengths")}`);
  }

  // Snapshot the pre-edit state so nothing is overwritten silently.
  const before = toGenerated(draft);
  await snapshotVersion(id, "Before manual edit", before);

  const d = parsed.data;
  await prisma.contentDraft.update({
    where: { id },
    data: {
      hook: d.hook,
      body: d.body,
      caption: d.body,
      cta: d.cta,
      hashtags: d.hashtags,
    },
  });

  revalidatePath(`/drafts/${id}`);
  redirect(`/drafts/${id}?notice=${encodeURIComponent("Edits saved (previous version kept in history)")}`);
}

/* ---------- restore a version ---------- */

export async function restoreVersion(formData: FormData) {
  const id = String(formData.get("id") ?? "");
  const versionId = String(formData.get("versionId") ?? "");
  await ownedDraft(id);

  const version = await prisma.draftVersion.findFirst({
    where: { id: versionId, draftId: id },
  });
  if (!version) redirect(`/drafts/${id}`);

  const current = await prisma.contentDraft.findUnique({ where: { id } });
  if (current) {
    await snapshotVersion(id, "Before restore", toGenerated(current));
  }

  const v = JSON.parse(version.content) as GeneratedDraft;
  await prisma.contentDraft.update({
    where: { id },
    data: {
      title: v.title,
      hook: v.hook,
      body: v.body,
      caption: v.caption,
      hashtags: v.hashtags.join(", "),
      cta: v.cta,
      visualNotes: v.visualDirection,
      ...(v.storyboard?.length ? { storyboard: JSON.stringify(v.storyboard) } : {}),
      ...(v.artboard ? { imagePrompt: JSON.stringify(v.artboard) } : {}),
      ...(v.design ? { designSpec: JSON.stringify(v.design) } : {}),
    },
  });

  revalidatePath(`/drafts/${id}`);
  redirect(`/drafts/${id}?notice=${encodeURIComponent(`Restored "${version.label}"`)}`);
}

/* ---------- delete ---------- */

export async function deleteDraft(formData: FormData) {
  const id = String(formData.get("id") ?? "");
  const user = await getCurrentUser();
  if (!user) redirect("/login");
  await prisma.contentDraft.deleteMany({ where: { id, userId: user.id } });
  redirect("/drafts");
}
