import { Badge, Card } from "@/components/ui";
import { isMovingFormat, type ArtboardSpec, type StoryboardShot } from "@/lib/generate";
import { estimateProduction } from "@/lib/visual";

/**
 * Creative assets for a draft: the generated artboard image, the animated
 * storyboard preview, the shot list, and an honest production estimate.
 *
 * Everything here is a plain server-rendered <img> pointing at the visual API
 * route — no client JavaScript, so it works in browsers that fail to hydrate.
 * Draftly's own generator and a configured LLM both produce the same spec
 * shape, so this component is identical in both modes.
 */

function parse<T>(raw: string | null, fallback: T): T {
  if (!raw) return fallback;
  try {
    return JSON.parse(raw) as T;
  } catch {
    return fallback;
  }
}

export function CreativeAssets({
  draftId,
  title,
  format,
  storyboardRaw,
  artboardRaw,
  designRaw,
  mode,
  model,
}: {
  draftId: string;
  title: string;
  format: string | null;
  storyboardRaw: string | null;
  artboardRaw: string | null;
  designRaw: string | null;
  mode: string;
  model: string | null;
}) {
  const storyboard = parse<StoryboardShot[]>(storyboardRaw, []);
  const artboard = parse<ArtboardSpec | null>(artboardRaw, null);
  const design = parse<{ palette?: string[]; typography?: string; layout?: string; motion?: string } | null>(
    designRaw,
    null
  );

  if (!artboard && !storyboard.length) {
    return (
      <Card className="flex flex-col gap-2">
        <h2 className="font-display font-semibold">Generated visual</h2>
        <p className="text-sm text-text-muted">
          No visual assets were generated for this draft yet. Regenerate the
          draft or use an improvement action to create visuals.
        </p>
      </Card>
    );
  }

  const moving = isMovingFormat(format ?? "");
  const estimate = storyboard.length ? estimateProduction(storyboard, moving) : null;
  const aspect = artboard?.aspect ?? "square";
  const imgClass =
    aspect === "portrait"
      ? "mx-auto w-full max-w-[300px] rounded-xl border border-line"
      : "w-full rounded-xl border border-line";

  return (
    <>
      {/* Generation provenance — never let a demo draft look like AI output */}
      <Card className="flex flex-wrap items-center justify-between gap-3">
        <div className="flex flex-wrap items-center gap-2">
          <span className="font-mono text-xs uppercase tracking-wider text-text-faint">
            Generated by
          </span>
          {mode === "llm" ? (
            <Badge tone="success">AI model{model ? ` · ${model}` : ""}</Badge>
          ) : (
            <Badge tone="warning">Built-in generator (demo mode)</Badge>
          )}
          {format && <Badge tone="accent">{format.replace(/_/g, " ")}</Badge>}
        </div>
        <p className="text-xs text-text-faint">
          {mode === "llm"
            ? "This draft came from a configured AI provider."
            : "No AI provider is configured, so Draftly's deterministic generator produced this. It follows your brand inputs exactly, but it is not an LLM."}
        </p>
      </Card>

      {/* Visual asset */}
      {artboard && (
        <Card className="flex flex-col gap-4">
          <div className="flex flex-wrap items-center justify-between gap-3">
            <h2 className="font-display font-semibold">Generated visual</h2>
            <div className="flex flex-wrap gap-2">
              <a
                href={`/api/drafts/${draftId}/visual?kind=artboard`}
                target="_blank"
                rel="noreferrer"
                className="rounded-full border border-line bg-surface-2 px-3 py-1.5 text-xs text-text-muted hover:border-accent hover:text-text"
              >
                Open full size
              </a>
              <a
                href={`/api/drafts/${draftId}/visual?kind=artboard&download=1`}
                className="rounded-full border border-line bg-surface-2 px-3 py-1.5 text-xs text-text-muted hover:border-accent hover:text-text"
              >
                Download SVG
              </a>
            </div>
          </div>

          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={`/api/drafts/${draftId}/visual?kind=artboard`}
            alt={`Generated ${aspect} artboard for ${title}`}
            className={imgClass}
            width={aspect === "landscape" ? 1600 : 1080}
            height={aspect === "portrait" ? 1350 : aspect === "landscape" ? 900 : 1080}
          />

          <div className="flex flex-col gap-2 text-sm">
            <p className="text-text-muted">{artboard.artDirection}</p>
            <div className="flex flex-wrap items-center gap-3">
              <span className="font-mono text-xs uppercase tracking-wider text-text-faint">
                Palette
              </span>
              {[artboard.palette.bg, artboard.palette.surface, artboard.palette.accent, artboard.palette.accent2, artboard.palette.fg].map(
                (c) => (
                  <span key={c} className="flex items-center gap-1.5">
                    <span
                      className="inline-block h-4 w-4 rounded border border-line"
                      style={{ backgroundColor: c }}
                      aria-hidden
                    />
                    <code className="text-xs text-text-faint">{c}</code>
                  </span>
                )
              )}
            </div>
            <p className="text-xs text-text-faint">
              This is a real generated image file (SVG) computed from your brand
              palette and the draft&apos;s headline — not a stock photo. It is designed
              artwork, not an AI diffusion image.
            </p>
          </div>
        </Card>
      )}

      {/* Animated storyboard preview */}
      {moving && storyboard.length > 0 && (
        <Card className="flex flex-col gap-4">
          <div className="flex flex-wrap items-center justify-between gap-3">
            <h2 className="font-display font-semibold">Animated preview</h2>
            <div className="flex flex-wrap gap-2">
              <a
                href={`/api/drafts/${draftId}/visual?kind=reel`}
                target="_blank"
                rel="noreferrer"
                className="rounded-full border border-line bg-surface-2 px-3 py-1.5 text-xs text-text-muted hover:border-accent hover:text-text"
              >
                Open full size
              </a>
              <a
                href={`/api/drafts/${draftId}/visual?kind=reel&download=1`}
                className="rounded-full border border-line bg-surface-2 px-3 py-1.5 text-xs text-text-muted hover:border-accent hover:text-text"
              >
                Download SVG
              </a>
            </div>
          </div>

          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={`/api/drafts/${draftId}/visual?kind=reel`}
            alt={`Animated ${storyboard.length}-shot preview for ${title}`}
            className="mx-auto w-full max-w-[300px] rounded-xl border border-line"
            width={1080}
            height={1350}
          />

          <p className="text-xs text-text-faint">
            A motion preview of the shot plan that plays in your browser — it
            animates your actual storyboard beats. It is a storyboard animatic,
            not a rendered video file.
          </p>
        </Card>
      )}

      {/* Storyboard / shot list */}
      {storyboard.length > 0 && (
        <Card className="flex flex-col gap-4">
          <h2 className="font-display font-semibold">
            {moving ? "Shot list" : "Visual plan"}
          </h2>
          <ol className="flex flex-col gap-3">
            {storyboard.map((s) => (
              <li
                key={s.index}
                className="flex flex-col gap-1.5 rounded-lg border border-line bg-surface-2 px-4 py-3"
              >
                <div className="flex flex-wrap items-center gap-2">
                  <span className="font-mono text-xs font-semibold text-accent2">
                    SHOT {s.index}
                  </span>
                  {s.timecode && s.timecode !== "—" && (
                    <Badge>{s.timecode}</Badge>
                  )}
                  {s.transition && (
                    <span className="text-xs text-text-faint">{s.transition}</span>
                  )}
                </div>
                <p className="text-sm leading-relaxed">{s.shot}</p>
                {s.onScreen && (
                  <p className="text-sm text-text-muted">
                    <span className="font-mono text-xs uppercase tracking-wider text-text-faint">
                      On screen ·{" "}
                    </span>
                    {s.onScreen}
                  </p>
                )}
                {s.voiceover && s.voiceover !== "—" && (
                  <p className="text-sm italic text-text-muted">
                    <span className="font-mono text-xs uppercase not-italic tracking-wider text-text-faint">
                      VO ·{" "}
                    </span>
                    {s.voiceover}
                  </p>
                )}
              </li>
            ))}
          </ol>
        </Card>
      )}

      {/* Design spec */}
      {design && (design.typography || design.motion) && (
        <Card className="flex flex-col gap-2">
          <h2 className="font-display font-semibold">Design spec</h2>
          <dl className="flex flex-col gap-1.5 text-sm">
            {design.typography && (
              <Spec label="Typography" value={design.typography} />
            )}
            {design.layout && <Spec label="Layout" value={design.layout} />}
            {design.motion && <Spec label="Motion" value={design.motion} />}
          </dl>
        </Card>
      )}

      {/* Production estimate */}
      {estimate && moving && (
        <Card className="flex flex-col gap-2">
          <h2 className="font-display font-semibold">What it takes to shoot this</h2>
          <p className="text-xs text-text-faint">
            Draftly&apos;s own estimate for producing this storyboard with a small
            team. It is a planning starting point, not a quote.
          </p>
          <dl className="mt-1 flex flex-col gap-1.5 text-sm">
            <Spec label="Crew" value={estimate.crew} />
            <Spec label="Time" value={estimate.hours} />
            <Spec label="Location" value={estimate.locations} />
            <Spec label="Kit" value={estimate.kit.join(" · ")} />
            <Spec label="Post" value={estimate.postNotes} />
          </dl>
        </Card>
      )}
    </>
  );
}

function Spec({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex flex-col gap-0.5 sm:flex-row sm:gap-4">
      <dt className="w-28 shrink-0 text-text-faint">{label}</dt>
      <dd className="text-text-muted">{value}</dd>
    </div>
  );
}